DROP DATABASE IF EXISTS DBCLINICAMEDICA;

CREATE DATABASE DBCLINICAMEDICA;

USE DBCLINICAMEDICA;

CREATE TABLE PACIENTE(
	IDPACIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150),
    CPF VARCHAR(11),
    TELEFONE VARCHAR(11),
    EMAIL VARCHAR(100),
    SEXO ENUM("M", "F"),
    TIPO_SANGUINEO VARCHAR(3),
    RUA VARCHAR(100),
    NUMERO INT,
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    ESTADO CHAR(2),
    CEP VARCHAR(8)
);

CREATE TABLE USUARIO(
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(45) NOT NULL UNIQUE,
    SENHA VARCHAR(45) NOT NULL,
    NIVEL ENUM("Médico", "Funcionário", "Admin")
);

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150),
    CPF VARCHAR(11),
    TELEFONE VARCHAR(11),
    EMAIL VARCHAR(100),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
);

CREATE TABLE MEDICO(
	IDMEDICO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150),
    CPF VARCHAR(11),
    TELEFONE VARCHAR(11),
    CELULAR VARCHAR(11),
    IDENDERECO INT,
    EMAIL VARCHAR(100),
    CRM VARCHAR(13),
    ESPECIALIDADE VARCHAR(100),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
);

CREATE TABLE CONSULTA(
	IDCONSULTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATA_CONSULTA DATETIME,
	IDPACIENTE INT NOT NULL,
	IDMEDICO INT NOT NULL,
	IDFUNCIONARIO INT NOT NULL,
	FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE),
	FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (IDMEDICO),
    FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO)
);

CREATE TABLE PRONTUARIO(
	IDPRONTUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDPACIENTE INT NOT NULL,
	IDMEDICO INT NOT NULL,
	OBSERVACOES VARCHAR(1000),
    DATA_PRONTUARIO DATE,
	FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE),
	FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (IDMEDICO)
);

INSERT INTO USUARIO (USUARIO, SENHA, NIVEL) VALUES ("admin", "admin", "Admin");