DROP DATABASE IF EXISTS DBCLINICAMEDICA;

CREATE DATABASE DBCLINICAMEDICA;

USE DBCLINICAMEDICA;

CREATE TABLE USUARIO(
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(45) NOT NULL UNIQUE,
    SENHA VARCHAR(45) NOT NULL,
    NIVEL ENUM("Médico", "Funcionário", "Admin")
);

CREATE TABLE PACIENTE(
	IDPACIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SEXO ENUM("Masculino", "Feminino") NOT NULL,
    TIPO_SANGUINEO VARCHAR(3) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CONVENIO ENUM("Particular", "Unimed", "Agemed", "Amil", "SulAmerica Saúde", "One Health", "Bradesco Saúde ", "Golden Cross", "Intermédica", "Notre Dame Seguro Saúde"),
    RUA VARCHAR(100) NOT NULL,
    NUMERO INT NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP VARCHAR(9) NOT NULL
);

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
);

CREATE TABLE MEDICO(
	IDMEDICO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CRM VARCHAR(13) NOT NULL,
    ESPECIALIDADE VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
);

CREATE TABLE CONSULTA(
	IDCONSULTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATA_CONSULTA DATETIME NOT NULL,
	IDPACIENTE INT NOT NULL,
	IDMEDICO INT NOT NULL,
	IDFUNCIONARIO INT NOT NULL,
	FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE),
	FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (IDMEDICO),
    FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO)
);

CREATE TABLE PRONTUARIO(
	IDPRONTUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDPACIENTE INT NOT NULL,
	IDMEDICO INT NOT NULL,
	OBSERVACOES VARCHAR(1000),
    DATA_PRONTUARIO DATE NOT NULL,
	FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE),
	FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (IDMEDICO)
);